### ISSUE TITLE
Integration stopped working suddenly

### ISSUE THREAD

**Issue by Auxx** [morosanmihail/HA-LondonTfL#11] opened 2022-05-24 09:58 UTC
Integration stopped working overnight. Might be that TfL API was changed or got broken?

So this night the following log was produced:

```
Logger: homeassistant.helpers.entity
Source: custom_components/london_tfl/tfl_data.py:61
Integration: London TfL ([documentation](https://github.com/morosanmihail/HA-LondonTfL), [issues](https://github.com/morosanmihail/HA-LondonTfL/issues))
First occurred: 01:57:32 (1 occurrences)
Last logged: 01:57:32
Update for sensor.london_tfl_tfl_rail_910ghayesah fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/config/custom_components/london_tfl/sensor.py", line 178, in async_update
    self._tfl_data.sort_data(self.max_items)
  File "/config/custom_components/london_tfl/tfl_data.py", line 60, in sort_data
    self._api_json = sorted(
  File "/config/custom_components/london_tfl/tfl_data.py", line 61, in <lambda>
    self._raw_result, key=lambda i: i['expectedArrival'], reverse=False
TypeError: string indices must be integers
```

I tried to remove and re-add the integration, but that fails with the following:

```
Logger: aiohttp.server
Source: custom_components/london_tfl/config_flow.py:56
Integration: London TfL ([documentation](https://github.com/morosanmihail/HA-LondonTfL), [issues](https://github.com/morosanmihail/HA-LondonTfL/issues))
First occurred: 10:49:55 (3 occurrences)
Last logged: 10:51:11
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 173, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/london_tfl/config_flow.py", line 56, in async_step_user
    lines = {item['id']: item['name'] for item in result}
  File "/config/custom_components/london_tfl/config_flow.py", line 56, in <dictcomp>
    lines = {item['id']: item['name'] for item in result}
TypeError: string indices must be integers
```

**Comment by morosanmihail** [comment] 2022-05-25 15:08
That seems like a very weird error. 

My test instances seem fine, but if you give me the station you're trying to track, I'll see if it's the API that's causing some new behaviour.

**Comment by morosanmihail** [comment] 2022-05-29 14:49
That seems really weird. Thank you for the info, I'll try to see if I can get a mitigation in place now, but I sadly won't have much time in the next couple of weeks if it doesn't work.

**Comment by morosanmihail** [comment] 2022-05-29 15:28
Ah, found the issues! It was the same root cause as another issue. Should be fixed.

https://github.com/morosanmihail/HA-LondonTfL/releases/tag/v0.3.1

**Closed by morosanmihail** 2022-05-29 15:28 UTC

**Comment by Auxx** [comment] 2022-05-29 15:32
It's working now, thank you very much!
